name: add-vs-test-project
author: gendloop
description: 'add-vs-test-project'
inputs:
# Required
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    - name: get-repo-name
      id: get-repo-name
      shell: bash
      run: |
        git pull
        repo_name=${GITHUB_REPOSITORY#*/}
        echo "reponame=$repo_name" >> "$GITHUB_OUTPUT"

    - name: check-vs-solution-file
      id: check-vs-solution-file
      shell: pwsh
      run: |
        $sln_file = "${{ steps.get-repo-name.outputs.reponame }}.sln"
        $result = Test-Path $sln_file
        if ($result -eq $true) {
          echo "Locate file $sln_file"
          "result=true" >> $env:GITHUB_OUTPUT
        }
        else {
          echo "Fail to locate file $sln_file"
          "result=false" >> $env:GITHUB_OUTPUT
        }

    - name: add-vs-test-project
      if: ${{ steps.check-vs-solution-file.outputs.result == 'true' }}
      shell: bash
      run: |
        # copy packages
        # cp -r -f ${{ github.action_path }}/packages .

        # copy tests
        cp -r -f ${{ github.action_path }}/tests .

        # copy sln
        cp -f "${{ github.action_path }}/docs/NewProject.sln" "${{ steps.get-repo-name.outputs.reponame }}.sln"

        # copy project
        mkdir ${{ steps.get-repo-name.outputs.reponame }}UTest
        cp -f "${{ github.action_path }}/docs/NewProjectUTest/NewProjectUTest.vcxproj" "./${{ steps.get-repo-name.outputs.reponame }}UTest/${{ steps.get-repo-name.outputs.reponame }}UTest.vcxproj"
        cp -f "${{ github.action_path }}/docs/NewProjectUTest/packages.config" "./${{ steps.get-repo-name.outputs.reponame }}UTest/packages.config"

    - name: create-vs-test-project
      if: ${{ steps.check-vs-solution-file.outputs.result == 'false' }}
      shell: bash
      run: |
        # copy packages
        # cp -r -f ${{ github.action_path }}/packages .

        # copy tests
        cp -r -f ${{ github.action_path }}/tests .

        # copy sln
        cp -f "${{ github.action_path }}/docs/NewProjectCreate.sln" "${{ steps.get-repo-name.outputs.reponame }}.sln"

        # copy project
        mkdir ${{ steps.get-repo-name.outputs.reponame }}
        cp -f "${{ github.action_path }}/docs/NewProjectUTest/NewProjectUTest.vcxproj" "./${{ steps.get-repo-name.outputs.reponame }}/${{ steps.get-repo-name.outputs.reponame }}.vcxproj"
        cp -f "${{ github.action_path }}/docs/NewProjectUTest/packages.config" "./${{ steps.get-repo-name.outputs.reponame }}/packages.config"

    - name: git-push
      if: ${{ steps.check-vs-solution-file.outputs.result == 'true' }}
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "feat: add project \\`${{ steps.get-repo-name.outputs.reponame }}UTest\\` "

    - name: git-push
      if: ${{ steps.check-vs-solution-file.outputs.result == 'false' }}
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "feat: create project \\`${{ steps.get-repo-name.outputs.reponame }}\\` "

    - name: replace-RepoName
      # if: ${{ steps.check-vs-solution-file.outputs.result == 'true' }}
      uses: gendloop/replace-str@v1.0.1
      with:
        token: ${{ github.token }}
        path-to-replace: ${{ steps.get-repo-name.outputs.reponame }}.sln
        replace-to-path: ${{ steps.get-repo-name.outputs.reponame }}.sln
        str-to-replace: "NewProject"
        replace-to-str: ${{ steps.get-repo-name.outputs.reponame }}
